# Generated by Django 3.2.4 on 2021-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210630_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
