# Generated by Django 3.2.4 on 2021-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='/prophile_photos/instagram_default.png', null=True, upload_to='prophile_photos'),
        ),
    ]
