# Generated by Django 3.2.4 on 2021-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default1.jpg', null=True, upload_to='prophile_photos'),
        ),
    ]
