# Generated by Django 3.2.4 on 2021-07-10 13:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloh', '0004_auto_20210630_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addermodel',
            name='population',
        ),
        migrations.RemoveField(
            model_name='addermodel',
            name='specify',
        ),
        migrations.AddField(
            model_name='areacategorymodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areacategorymodel',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='areacategorymodel',
            name='economic_region',
            field=models.CharField(choices=[('HEÇBİRİ', '-'), ('ARAN', 'ARAN'), ('GƏNCƏ-QAZAX', 'GƏNCƏ-QAZAX'), ('ABŞERON', 'ABŞERON'), ('LƏNKƏRAN', 'LƏNKƏRAN'), ('NAXÇIVAN', 'NAXÇIVAN'), ('KƏLBƏCƏR-LAÇIN', 'KƏLBƏCƏR-LAÇIN'), ('DAĞLIQ QARABAĞ', 'DAĞLIQ QARABAĞ'), ('DAĞLIQ ŞİRVAN', 'DAĞLIQ ŞİRVAN'), ('QUBA-XAÇMAZ', 'QUBA-XAÇMAZ'), ('ŞƏKİ-ZAQATALA', 'ŞƏKİ-ZAQATALA')], default='HEÇBİRİ', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='areacategorymodel',
            name='population',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='areacategorymodel',
            name='specify',
            field=models.CharField(choices=[('DAĞLIQ', 'DAĞLIQ'), ('DÜZƏNLİK', 'DÜZƏNLİK'), ('DƏNİZQIRAĞI', 'DƏNİZQIRAĞI'), ('SƏHRA', 'SƏHRA')], default='DAĞLIQ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addermodel',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
