# Generated by Django 3.2.4 on 2021-07-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloh', '0006_alter_addermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addermodel',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entr', to='bloh.commentarticle'),
        ),
    ]
