# Generated by Django 3.2.4 on 2021-07-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloh', '0007_addermodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addermodel',
            name='comments',
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bloh.addermodel'),
        ),
    ]
