# Generated by Django 3.2.4 on 2021-07-25 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloh', '0008_auto_20210724_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
